version: '3.1'

services:
  shop_database:
    image: postgres:9.6.4
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres